// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"utils/Util_MessageProcessor","status":true,"description":"","parameters":{}},
{"name":"globals/enums","status":true,"description":"","parameters":{}},
{"name":"objects/Game_Server","status":true,"description":"","parameters":{}},
{"name":"objects/Game_Room","status":true,"description":"","parameters":{}},
{"name":"objects/Game_OnlinePlayer","status":true,"description":"","parameters":{}}
];
