// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"dev/MZPlusQuickStart","status":true,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"true"}},
{"name":"globals/enums","status":true,"description":"","parameters":{}},
{"name":"utils/message_processor/Util_MessageProcessor","status":true,"description":"","parameters":{}},
{"name":"utils/message_processor/MP_Connection","status":true,"description":"","parameters":{}},
{"name":"utils/message_processor/MP_Movement","status":true,"description":"","parameters":{}},
{"name":"online_player/Window_Username","status":true,"description":"","parameters":{}},
{"name":"online_player/Game_OnlinePlayer","status":true,"description":"","parameters":{}},
{"name":"rmmz/Game_Player","status":true,"description":"","parameters":{}},
{"name":"rmmz/Game_Event","status":true,"description":"","parameters":{}},
{"name":"server/Game_Server","status":true,"description":"","parameters":{}},
{"name":"room/Game_Room","status":true,"description":"","parameters":{}},
{"name":"lobby/Game_Lobby","status":true,"description":"","parameters":{}},
{"name":"chat/Game_Chat","status":true,"description":"","parameters":{}},
{"name":"chat/input/Game_ChatInput","status":true,"description":"","parameters":{}},
{"name":"chat/input/Window_ChatInput","status":true,"description":"","parameters":{}}
];
