// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"dev/MZPlusQuickStart","status":true,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"true"}},
{"name":"globals/enums","status":true,"description":"","parameters":{}},
{"name":"utils/Util_MessageProcessor","status":true,"description":"","parameters":{}},
{"name":"server/Game_Server","status":true,"description":"","parameters":{}},
{"name":"server/Game_Room","status":true,"description":"","parameters":{}},
{"name":"onlinePlayer/Game_Event","status":true,"description":"","parameters":{}},
{"name":"onlinePlayer/Game_OnlinePlayer","status":true,"description":"","parameters":{}},
{"name":"onlinePlayer/Window_Username","status":true,"description":"","parameters":{}},
{"name":"lobby/Game_Lobby","status":true,"description":"","parameters":{}}
];
